/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tarea3.calculadoraartimetica;

import tarea3.calculadoraartimetica.ShuntingYardAlgorithm;

import java.util.Arrays;
import java.util.List;


public class App {
    public static void main(String[] args) {
        List<String> tokens = Arrays.asList("3", "+", "4","+","2"); // Replace with your tokens
        List<String> output = ShuntingYardAlgorithm.shuntingYard(tokens);
        // Print the output
        for (String token : output) {
            System.out.println(token);
        }
    }
}
