/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tarea3.calculadoraartimetica;


import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.Arrays;
import java.util.List;

class AppTest {
    @Test
    void testMain() {
        List<String> tokens = Arrays.asList("3", "+", "4","-2"); // Replace with your tokens
        List<String> output = ShuntingYardAlgorithm.shuntingYard(tokens);
        // Print the output
        for (String token : output) {
            System.out.println(token);
        }
    }
}
